# Generated by Django 5.1.4 on 2025-02-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='supplier_sub_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
