# Generated by Django 5.1.4 on 2025-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_suppliermodel_supplier_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='supplier_account_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
