# Generated by Django 5.1.4 on 2025-02-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_suppliermodel_supplier_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='suppliermodel',
            name='supplier_address',
        ),
    ]
