# Generated by Django 5.1.4 on 2025-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_customermodel_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='customer_address_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='supplier_address_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='supplier_address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
