# Generated by Django 5.1.4 on 2025-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customermodel_customer_address_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_address_1',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_address_2',
        ),
        migrations.RemoveField(
            model_name='suppliermodel',
            name='supplier_address_1',
        ),
        migrations.RemoveField(
            model_name='suppliermodel',
            name='supplier_address_2',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='supplier_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
