# Generated by Django 5.1.4 on 2025-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_customermodel_customer_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_account_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
