# Generated by Django 5.1.4 on 2025-02-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_customermodel_customer_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippedfrommodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
