# Generated by Django 5.1.4 on 2025-02-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_shippedfrommodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproductmodel',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
