# Generated by Django 5.1.4 on 2025-02-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billproductmodel_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproductmodel',
            name='total_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
