# Generated by Django 5.1.4 on 2025-02-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_billproductmodel_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproductmodel',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='billmodel',
            name='total_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
