# Generated by Django 5.1.4 on 2025-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_billproductmodel_total_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
