# Generated by Django 5.1.4 on 2025-02-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_billmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproductmodel',
            name='product_code',
            field=models.CharField(max_length=50),
        ),
    ]
