# Generated by Django 5.2 on 2025-04-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_billmodel_is_estimation_alter_billmodel_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproductmodel',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.productmodel'),
        ),
    ]
