# Generated by Django 5.2 on 2025-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_billproductmodel_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='reorder_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
