# Generated by Django 5.2 on 2025-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_productmodel_reorder_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasestockproductmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='purchasestockproductmodel',
            name='buy_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchasestockproductmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='cgst_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='cgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='discount_amount_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='discount_amount_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='discount_percentage_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='discount_percentage_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='discount_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='grandTotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='igst_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='igst_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='sgst_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='sgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='totalTax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasestockproductmodel',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
